package MPSListener.plugin.dataClasses.emf;

/*Generated by MPS */

import java.util.List;
import java.util.Collections;

public class fileData {
  private String type;
  private String id;
  private String name;
  private List<input> inputs;
  private List<output> outputs;
  private List<states> states;

  public fileData(String tyoe, String id, String name, List<input> inputs, List<output> outputs, List<states> states) {
    this.type = type;
    this.id = id;
    this.name = name;
    this.inputs = inputs;
    this.outputs = outputs;
    this.states = states;
  }

  public String getType() {
    return new String(this.type);
  }

  public String getID() {
    return new String(this.id);
  }

  public String getName() {
    return new String(this.name);
  }

  public List<input> getInputs() {
    return Collections.unmodifiableList(this.inputs);
  }

  public List<output> getOutputs() {
    return Collections.unmodifiableList(this.outputs);
  }

  public List<states> getStates() {
    return Collections.unmodifiableList(this.states);
  }
}
