package MPSListener.plugin.dataClasses.emf;

/*Generated by MPS */

import java.util.HashMap;

public class input {
  private String id;
  private String name;
  private String description;

  public input(HashMap<String, String> inputMap) {
    this.id = inputMap.get("$id");
    this.name = inputMap.get("name");
    this.description = inputMap.get("description");
  }

  public String getId() {
    return new String(this.id);
  }

  public String getName() {
    return new String(this.name);
  }

  public String getDescription() {
    return new String(this.description);
  }
}
