package MPSListener.plugin.dataClasses.emf;

/*Generated by MPS */

import java.util.HashMap;

public class output {
  private String id;
  private String name;

  public output(HashMap<String, String> outputMap) {
    this.id = outputMap.get("$id");
    this.name = outputMap.get("name");
  }

  public String getId() {
    return new String(this.id);
  }

  public String getName() {
    return new String(this.name);
  }
}
