package MPSListener.plugin.dataClasses.emf;

/*Generated by MPS */

import java.util.HashMap;

public class states {
  private String id;
  private String name;
  /**
   * To consider: States seem to have a name and an output has reference, example does not seem to have any link to outputs, be warned.
   */
  public states(HashMap<String, String> statesMap) {
    this.id = statesMap.get("$id");
    this.name = statesMap.get("name");
  }

  public String getId() {
    return this.id;
  }

  public String getName() {
    return this.name;
  }

}
