package MPSListener.plugin.dataClasses.emf.patches;

/*Generated by MPS */

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public class Data {
  private String type;
  @JsonProperty(value = "data")
  private List<Patch> data;

  public Data(String type, List<Patch> patch) {
    super();
    this.type = type;
    this.data = patch;
  }
  public Data() {
  }
  public String getType() {
    return this.type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public List<Patch> getData() {
    return this.data;
  }
  public void setData(List<Patch> patch) {
    this.data = patch;
  }
}
