package MPSListener.plugin.dataClasses.emf.patches;

/*Generated by MPS */

import java.util.Optional;

public class Patch {
  private String op;
  private String path;

  /**
   * Optional fields as some type of patches do not have the fields below.
   */
  private Optional<String> from;
  private Optional<String> value;
  public Patch(String op, String path, String from, String value) {
    this.op = op;
    this.path = path;
    this.from = Optional.ofNullable(from);
    this.value = Optional.ofNullable(value);
  }
  public String getOp() {
    return this.op;
  }
  public String getPath() {
    return this.path;
  }

  public Optional<String> getFrom() {
    return this.from;
  }
  public Optional<String> getValue() {
    return this.value;
  }
}
