package MPSListener.plugin.dataClasses.emf.patches;

/*Generated by MPS */

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;
import MPSListener.plugin.emfModelServer.parsers.PatchParser;

@JsonInclude(value = JsonInclude.Include.NON_NULL)
public class Patch<T> {
  private String op;
  private String path;

  /**
   * Optional fields as some type of patches do not have the fields below.
   */
  private String from;

  private T value;

  public Patch(String op, String path, String from, T value) {
    this.op = op;
    this.path = path;
    this.from = from;
    this.value = value;
  }
  public String getOp() {
    return this.op;
  }
  public String getPath() {
    return this.path;
  }

  public String getFrom() {
    return this.from;
  }
  public T getValue() {
    return this.value;
  }

  public static void main(String[] args) {
    String patches = "[{\"op\":\"remove\",\"path\":\"/inputs/1/name\"},{\"op\":\"replace\",\"path\":\"/inputs/2/name\",\"value\":\"Go\"},{\"op\":\"add\",\"path\":\"/inputs/-\",\"value\":{\"$id\":\"//@inputs.3\",\"name\":\"Wait\"}},{\"op\":\"replace\",\"path\":\"/transitions/0/input/$ref\",\"value\":\"//@inputs.3\"},{\"op\":\"replace\",\"path\":\"/transitions/1/input/$ref\",\"value\":\"//@inputs.2\"},{\"op\":\"replace\",\"path\":\"/transitions/3/input/$ref\",\"value\":\"//@inputs.3\"}]";
    List<Patch> allPatches = PatchParser.getPatch(patches);
    String smth = null;
  }
}
