package MPSListener.plugin.dataClasses.emf.patches;

/*Generated by MPS */

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(value = JsonInclude.Include.NON_NULL)
public class Patch<T> {
  private String op;
  private String path;

  /**
   * Optional fields as some type of patches do not have the fields below.
   */
  private String from;

  private T value;

  public Patch(String op, String path, String from, T value) {
    this.op = op;
    this.path = path;
    this.from = from;
    this.value = value;
  }
  public String getOp() {
    return this.op;
  }
  public String getPath() {
    return this.path;
  }

  public String getFrom() {
    return this.from;
  }
  public T getValue() {
    return this.value;
  }
}
