package MPSListener.plugin.dataClasses.emf.patches;

/*Generated by MPS */


public class Root {
  private Data data;
  public Root() {
  }
  public Root(Data data) {
    super();
    this.data = data;
  }
  public Data getData() {
    return this.data;
  }
  public void setData(Data data) {
    this.data = data;
  }
}
