package MPSListener.EMF;

/*Generated by MPS */

import ecoreRepresentation.Root;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.log4j.Logger;
import com.fasterxml.jackson.core.JsonProcessingException;

public class EMF_ecoreParser {
  private Root eCoreRoot;
  private ObjectMapper om;
  private EmfClient client;
  private Logger log;

  public EMF_ecoreParser() {

    this.om = new ObjectMapper();
    this.client = EmfClient.getInstance();
    this.log = Logger.getLogger(EMF_ecoreParser.class);
  }

  public Root parseEcore(String fileName) {
    this.client.getModel(fileName);
    try {
      this.eCoreRoot = this.om.readValue(fileName, Root.class);
    } catch (JsonProcessingException je) {
      log.error(je.getMessage());
    }
    return this.eCoreRoot;
  }

  public static void main(String[] args) {
    EMF_ecoreParser parser = new EMF_ecoreParser();
    Root root = parser.parseEcore("statemachine.ecore");
  }
}
