package MPSListener.EMF;

/*Generated by MPS */

import java.util.HashMap;

public class EMF_input {
  private String id;
  private String name;

  public EMF_input(HashMap<String, String> inputMap) {
    this.id = inputMap.get("$id");
    this.name = inputMap.get("name");
  }

  public String getId() {
    return new String(this.id);
  }

  public String getName() {
    return new String(this.name);
  }

}
