package MPSListener.plugin.emfModelServer;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpHeaders;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.HttpServerErrorException;
import org.apache.log4j.Level;
import org.apache.http.client.utils.URIBuilder;
import java.net.URISyntaxException;
import MPSListener.plugin.dataClasses.mps.PropertyChanged;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.core.JsonProcessingException;
import org.apache.log4j.BasicConfigurator;
import MPSListener.plugin.parsers.emf.EMF_parser;

public class EmfClient {
  private static final Logger LOG = LogManager.getLogger(EmfClient.class);
  private final String serverSocketAddress;
  private final String models;
  private final String currentModel;
  private final ObjectMapper om;
  private static EmfClient emfClient;
  private EmfClient() {
    this.serverSocketAddress = "http://localhost:8081/api/v2/";
    this.models = "models";
    this.currentModel = "SuperBrewer3000.json";
    this.om = new ObjectMapper();
  }

  public static EmfClient getInstance() {
    if (emfClient == null) {
      emfClient = new EmfClient();
    }
    return emfClient;
  }

  public String getAllModels() {
    if (LOG.isInfoEnabled()) {
      LOG.info("Getting all models....");
    }
    HttpHeaders headers = new HttpHeaders();
    RestTemplate restTemplate = new RestTemplate();
    ResponseEntity responseEntity = null;
    try {
      responseEntity = restTemplate.getForEntity(this.serverSocketAddress + this.models, String.class);
    } catch (HttpServerErrorException su) {
      if (LOG.isEnabledFor(Level.WARN)) {
        LOG.warn("Error getting all models");
      }
    }
    return responseEntity.getBody().toString();
  }

  public String getModel(String modelUri) {
    if (LOG.isInfoEnabled()) {
      LOG.info("Attempting to retrieve model:" + modelUri);
    }
    HttpHeaders headers = new HttpHeaders();
    RestTemplate restTemplate = new RestTemplate();
    ResponseEntity responseEntity = null;
    try {
      String queryAddress = new URIBuilder(this.serverSocketAddress + this.models).addParameter("modeluri", modelUri).build().toString();
      responseEntity = restTemplate.getForEntity(queryAddress, String.class);
    } catch (URISyntaxException se) {
      if (LOG.isInfoEnabled()) {
        LOG.info(se.getMessage());
      }
    }
    return responseEntity.getBody().toString();
  }

  public String getNodeFromModel(PropertyChanged propertyChanged) {
    String modelDetails = getModel(this.currentModel);
    String nodeDetails = "";
    try {
      JsonNode jsonNode = om.readTree(modelDetails);
      if (LOG.isInfoEnabled()) {
        LOG.info(jsonNode.toPrettyString());
      }
      nodeDetails = jsonNode.get(0).toPrettyString();
      if (LOG.isInfoEnabled()) {
        LOG.info(nodeDetails);
      }
    } catch (JsonProcessingException pe) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error(pe.getMessage());
      }
    }
    return nodeDetails;
  }

  public static void main(String[] args) {
    BasicConfigurator.configure();
    EmfClient emfServer = new EmfClient();
    System.out.println(emfServer.getModel("StateMachine.xmi"));
    EMF_parser emf_synchroniseModel = new EMF_parser();
  }
}
