package MPSListener.plugin.synchronise;

/*Generated by MPS */

import MPSListener.plugin.dataClasses.emf.patches.Patch;

public class IncomingChangeValidator {
  private static IncomingChangeValidator instance;

  private Patch lastPatch;

  public IncomingChangeValidator getInstance() {
    if (instance == null) {
      instance = new IncomingChangeValidator();
    }
    return instance;
  }
  private IncomingChangeValidator() {

  }
  public void setLastPatch(Patch patch) {
    this.lastPatch = patch;
  }

}
