package MPSListener.plugin.synchronise;

/*Generated by MPS */

import MPSListener.plugin.dataClasses.emf.fileData;
import org.jetbrains.mps.openapi.model.SNode;

public class Mapper {
  public Mapper(fileData emfFileData, SNode modelInstance) {
  }
}
