package MPSListener.plugin.synchronise;

/*Generated by MPS */

import MPSListener.plugin.dataClasses.emf.fileData;

public class Mapper {
  public Mapper(fileData emfFileData, MPSListener.plugin.dataClasses.mps.fileData mpsFileData) {
  }
}
