package MPSListener.plugin.synchronise;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import MPSListener.plugin.dataClasses.emf.fileData;
import org.jetbrains.mps.openapi.module.SRepository;
import MPSListener.plugin.listener.MyListener;
import java.util.List;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.smodel.MPSModuleRepository;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Iterator;
import org.jetbrains.mps.openapi.model.SNode;

public class MPS_synchroniseWithEMF {
  private static final Logger LOG = LogManager.getLogger(MPS_synchroniseWithEMF.class);
  private fileData emfFileData;
  private SRepository myRepositary;
  private MPSListener.plugin.dataClasses.mps.fileData mpsFileData;
  private MyListener myListener;

  protected List<SRepository> myRepos;
  protected List<SModule> myModules;
  protected List<SModel> myModels;



  public MPS_synchroniseWithEMF(fileData emfFileData) {
    this.emfFileData = emfFileData;
    this.myRepositary = MPSModuleRepository.getInstance();
    this.myModules = ListSequence.fromList(new ArrayList<SModule>());
    this.myRepos = ListSequence.fromList(new ArrayList<SRepository>());
    this.myModels = ListSequence.fromList(new ArrayList<SModel>());
    start();
  }


  public void start() {
    myRepositary.getModelAccess().runReadAction(() -> {
      ListSequence.fromList(myRepos).addElement(myRepositary);
      for (SModule module : Sequence.fromIterable(myRepositary.getModules())) {
        for (SModel model : Sequence.fromIterable(module.getModels())) {
          ListSequence.fromList(myModels).addElement(model);
        }
        ListSequence.fromList(myModules).addElement(module);
      }
    });
  }

  private Boolean fileIsPresentLocally() {
    String fileName = emfFileData.getName();
    Iterator<SModule> moduleIterator = ListSequence.fromList(myModules).iterator();
    // Locate sandbox module
    while (moduleIterator.hasNext()) {
      SModule currentModule = moduleIterator.next();
      if (currentModule.getModuleName().toString().equals("sandbox")) {

        // For each model present, visit all instances to look for fileName
        Iterator<SModel> modelIterator = currentModule.getModels().iterator();
        while (modelIterator.hasNext()) {
          SModel currentModel = modelIterator.next();

          // Visit all instances of currentModel to look for fileName
          Iterator<SNode> nodeIterator = currentModel.getRootNodes().iterator();
          while (nodeIterator.hasNext()) {
            SNode currentNode = nodeIterator.next();
            if (currentNode.getName().toString().equals(fileName)) {
              Iterator<? extends SNode> modelInstanceChildren = currentNode.getChildren().iterator();
              parseModeldata(modelInstanceChildren);
              return true;
            }
          }
        }
      }
    }
    return false;
  }


  /**
   * Helper function for fileIsPresentLocally
   */
  private void parseModeldata(Iterator<? extends SNode> modelChildrenIterator) {
    this.mpsFileData.setModelName(emfFileData.getName());
    while (modelChildrenIterator.hasNext()) {
      SNode currentElement = modelChildrenIterator.next();
      switch (currentElement.getConcept().getName()) {
        case "Output":
          this.mpsFileData.appendOneToOutputs(currentElement);
        case "Input":
          this.mpsFileData.appendOneToInputs(currentElement);
        case "State":
          this.mpsFileData.appendOneToStates(currentElement);
      }
      if (LOG.isInfoEnabled()) {
        LOG.info(currentElement.getName());
      }
    }
  }

  public MPSListener.plugin.dataClasses.mps.fileData syncLocally() {
    if (fileIsPresentLocally()) {
      return this.mpsFileData;
    }
    return null;
  }
}
