package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class actionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "MPSListener.plugin.actionGroup_ActionGroup";

  public actionGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("actionGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    actionGroup_ActionGroup.this.addAction("MPSListener.plugin.actionTool_Action");
  }
}
