package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;
import MPSListener.plugin.specifyModel.StartPlugin;

public class ApplicationPlugin_AppPluginPart extends ApplicationPluginPart {
  private MyListener listener;
  private EMF_parser parser;
  private StartPlugin startPlugin;
  public ApplicationPlugin_AppPluginPart() {
  }
}
