package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;
import MPSListener.plugin.initiate.StartPlugin;

public class appPlugin_AppPluginPart extends ApplicationPluginPart {
  public appPlugin_AppPluginPart() {
  }
  @Override
  public void dispose() {
    if (StartPlugin.getInstance() != null) {
      StartPlugin.getInstance().stop();
    }
  }
}
