package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class collaborate_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "MPSListener.plugin.collaborate_ActionGroup";

  public collaborate_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("collaborate", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    collaborate_ActionGroup.this.addAction("MPSListener.plugin.Enable_Collaboration_Action");
    collaborate_ActionGroup.this.addAction("MPSListener.plugin.Disable_Collaboration_Action");
  }
}
