package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class Collaboration_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "MPSListener.plugin.Collaboration_ActionGroup";

  public Collaboration_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("Collaboration", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    Collaboration_ActionGroup.this.addAction("MPSListener.plugin.Enable_Collaboration_Action");
    Collaboration_ActionGroup.this.addAction("MPSListener.plugin.Disable_Collaboration_Action");
  }
}
