package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import MPSListener.plugin.initiate.StartPlugin;
import jetbrains.mps.ide.actions.MPSCommonDataKeys;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.project.MPSProject;

public class Enable_Collaboration_Action extends BaseAction {
  private static final Icon ICON = null;

  public Enable_Collaboration_Action() {
    super("Enable Collaboration", "", ICON);
    this.setIsAlwaysVisible(true);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    event.getPresentation().setEnabledAndVisible(StartPlugin.getInstance(event.getData(MPSCommonDataKeys.NODE), event.getData(MPSCommonDataKeys.MPS_PROJECT)).isRunning() == false);
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      SNode p = event.getData(MPSCommonDataKeys.NODE);
      if (p == null) {
        return false;
      }
    }
    {
      MPSProject p = event.getData(MPSCommonDataKeys.MPS_PROJECT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    Enable_Collaboration_Action.this.startCollaboration(event);
  }
  private void startCollaboration(final AnActionEvent event) {
    StartPlugin pluginLauncher = StartPlugin.getInstance();
    if (pluginLauncher != null) {
      // Plugin already running, change target.
      // TODO: Fix setting target properly, problem atm is the reference of a given node is stored in all of the other classes, so need to change target there too.
      pluginLauncher.changeTargetNode(event.getData(MPSCommonDataKeys.NODE));
    }
    if (pluginLauncher == null) {
      // Plugin not started yet, launch plugin.
      pluginLauncher = StartPlugin.getInstance(event.getData(MPSCommonDataKeys.NODE), event.getData(MPSCommonDataKeys.MPS_PROJECT));
    }
    pluginLauncher.start();
  }
}
