package MPSListener.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.SRepositoryListener;
import org.jetbrains.mps.openapi.module.SModuleListener;
import org.jetbrains.mps.openapi.model.SModelListener;
import org.jetbrains.mps.openapi.model.SNodeChangeListener;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.mps.openapi.module.SRepository;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.model.SModelReference;
import org.jetbrains.mps.openapi.module.SDependency;
import org.jetbrains.mps.openapi.language.SLanguage;
import org.jetbrains.mps.openapi.event.SPropertyChangeEvent;
import org.jetbrains.mps.openapi.event.SReferenceChangeEvent;
import org.jetbrains.mps.openapi.event.SNodeAddEvent;
import org.jetbrains.mps.openapi.event.SNodeRemoveEvent;

public class GlobalSModelListener implements SRepositoryListener, SModuleListener, SModelListener, SNodeChangeListener {
  private static final Logger LOG = LogManager.getLogger(GlobalSModelListener.class);

  protected SRepository myRepository;
  protected boolean myActive;

  protected List<SRepository> myRepos = ListSequence.fromList(new ArrayList<SRepository>());
  protected List<SModule> myModules = ListSequence.fromList(new ArrayList<SModule>());
  protected List<SModel> myModels = ListSequence.fromList(new ArrayList<SModel>());

  public GlobalSModelListener(SRepository repository) {
    myRepository = repository;
  }

  public void start() {
    myRepository.getModelAccess().runReadAction(() -> start(myRepository));
    myActive = true;
  }

  protected void start(SRepository repo) {
    ListSequence.fromList(myRepos).addElement(repo);
    repo.addRepositoryListener(this);
    for (SModule module : Sequence.fromIterable(myRepository.getModules())) {
      start(module);
    }
  }

  protected void start(SModule module) {
    ListSequence.fromList(myModules).addElement(module);
    module.addModuleListener(this);
    for (SModel model : Sequence.fromIterable(module.getModels())) {
      start(model);
    }
  }

  protected void start(SModel model) {
    ListSequence.fromList(myModels).addElement(model);
    model.addModelListener(this);
    model.addChangeListener(this);
  }

  public void stop() {
    myActive = false;
    myRepository.getModelAccess().runReadAction(() -> {
      stop(myRepository);
      for (SRepository repo : ListSequence.fromList(myRepos)) {
        repo.removeRepositoryListener(GlobalSModelListener.this);
      }
      for (SModule m : ListSequence.fromList(myModules)) {
        m.removeModuleListener(GlobalSModelListener.this);
      }
      for (SModel m : ListSequence.fromList(myModels)) {
        m.removeModelListener(GlobalSModelListener.this);
        m.removeChangeListener(GlobalSModelListener.this);
      }
    });
  }

  protected void stop(SRepository repo) {
    for (SModule module : Sequence.fromIterable(repo.getModules())) {
      stop(module);
    }
    repo.removeRepositoryListener(this);
    ListSequence.fromList(myRepos).removeElement(repo);
  }

  protected void stop(SModule module) {
    for (SModel model : Sequence.fromIterable(module.getModels())) {
      stop(model);
    }
    module.removeModuleListener(this);
    ListSequence.fromList(myModules).removeElement(module);
  }

  protected void stop(SModel model) {
    model.removeModelListener(this);
    model.removeChangeListener(this);
    ListSequence.fromList(myModels).removeElement(model);
  }

  @Override
  public void moduleAdded(@NotNull SModule module) {
    if (myActive) {
      start(module);
    }
    System.out.println("module added");
    if (LOG.isInfoEnabled()) {
      LOG.info("module added");
    }
  }
  @Override
  public void beforeModuleRemoved(@NotNull SModule module) {
    if (myActive) {
      stop(module);
    }
  }
  @Override
  public void moduleRemoved(@NotNull SModuleReference reference) {
    if (LOG.isInfoEnabled()) {
      LOG.info("module removed");
    }
  }
  @Override
  public void commandStarted(SRepository repository) {
    if (LOG.isInfoEnabled()) {
      LOG.info("Command started....");
    }
  }
  @Override
  public void commandFinished(SRepository repository) {
    SRepository repository1 = repository;
  }
  @Deprecated
  @Override
  public void updateStarted(SRepository repository) {
    if (LOG.isInfoEnabled()) {
      LOG.info(" update started");
    }
  }
  @Deprecated
  @Override
  public void updateFinished(SRepository repository) {
  }
  @Deprecated
  @Override
  public void repositoryCommandStarted(SRepository repository) {
  }
  @Deprecated
  @Override
  public void repositoryCommandFinished(SRepository repository) {
  }




  @Override
  public void modelAdded(SModule module, SModel model) {
    if (myActive) {
      start(model);
    }
    if (LOG.isInfoEnabled()) {
      LOG.info("model added");
    }
  }
  @Override
  public void beforeModelRemoved(SModule module, SModel model) {
    if (myActive) {
      stop(model);
    }
  }
  @Override
  public void modelRemoved(SModule module, SModelReference reference) {
  }
  @Override
  public void beforeModelRenamed(SModule module, SModel model, SModelReference reference) {
  }
  @Override
  public void modelRenamed(SModule module, SModel model, SModelReference reference) {
  }
  @Override
  public void dependencyAdded(SModule module, SDependency dependency) {
  }
  @Override
  public void dependencyRemoved(SModule module, SDependency dependency) {
  }
  @Override
  public void languageAdded(SModule module, SLanguage language) {
  }
  @Override
  public void languageRemoved(SModule module, SLanguage language) {
  }
  @Override
  public void moduleChanged(SModule module) {
    if (LOG.isInfoEnabled()) {
      LOG.info("module changed");
    }
  }


  @Override
  public void modelLoaded(SModel model, boolean partially) {
    if (LOG.isInfoEnabled()) {
      LOG.info(model.getName() + "loaded. Partial load:" + partially);
    }
  }
  @Override
  public void modelReplaced(SModel model) {
  }
  @Override
  public void modelUnloaded(SModel model) {
  }
  @Override
  public void modelSaved(SModel model) {
  }
  @Override
  public void modelAttached(SModel model, SRepository repository) {
  }
  @Override
  public void modelDetached(SModel model, SRepository repository) {
  }
  @Override
  public void conflictDetected(SModel model) {
  }
  @Override
  public void problemsDetected(SModel model, Iterable<SModel.Problem> iterable) {
  }




  @Override
  public void propertyChanged(@NotNull SPropertyChangeEvent event) {
  }
  @Override
  public void referenceChanged(@NotNull SReferenceChangeEvent event) {
  }
  @Override
  public void nodeAdded(@NotNull SNodeAddEvent event) {
    if (LOG.isInfoEnabled()) {
      LOG.info("node added");
    }
    if (LOG.isInfoEnabled()) {
      LOG.info(event.getParent().getName());
    }
    if (LOG.isInfoEnabled()) {
      LOG.info(event.getChild().getName());
    }
  }
  @Override
  public void nodeRemoved(@NotNull SNodeRemoveEvent event) {
  }

  public List<SRepository> getRepositary() {
    return this.myRepos;
  }
  public List<SModule> getModules() {
    return this.myModules;
  }
}
