package MPSListener.plugin;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.event.SPropertyChangeEvent;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.module.SModule;

public class MyListener extends GlobalSModelListener {
  private static final Logger LOG = LogManager.getLogger(MyListener.class);
  private EmfClient emfClient;
  private static MyListener myListener;
  private MyListener(SNode node) {
    super(node);
    this.emfClient = EmfClient.getInstance();
  }

  public static MyListener getInstance(SNode startingNode) {
    if (myListener == null) {
      System.out.println("Creating instance at MyListener.");
      myListener = new MyListener(startingNode);
    }
    return myListener;
  }

  @Override
  public void propertyChanged(@NotNull SPropertyChangeEvent event) {
    PropertyChanged propertyChanged = new PropertyChanged(event);
    System.out.println("hello");
    if (LOG.isInfoEnabled()) {
      LOG.info(propertyChanged.toString());
    }

    SModel sModel = event.getModel();
    SNode sNode = event.getNode();
    SModule sModule = event.getModel().getModule();
  }



}
