package MPSListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;

public class plugin_AppPluginPart extends ApplicationPluginPart {
  public plugin_AppPluginPart() {
  }
  @Override
  public void init() {
  }
  @Override
  public void dispose() {

  }
}
