package MPSListener.plugin;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.eclipse.emfcloud.modelserver.client.ModelServerClient;
import org.eclipse.emfcloud.modelserver.client.SubscriptionListener;
import org.eclipse.emfcloud.modelserver.example.client.ExampleXMISubscriptionListener;
import org.eclipse.emf.ecore.EObject;

public class WebSocketClient {
  private static final Logger LOG = LogManager.getLogger(WebSocketClient.class);
  private ModelServerClient modelServerClient;
  private String webSocketAddress;
  private String subscriptionID;
  public WebSocketClient() {
    this.webSocketAddress = "http://localhost:8081/api/v2/";
    this.subscriptionID = "StateMachine.xmi";

    SubscriptionListener listener = new ExampleXMISubscriptionListener(this.subscriptionID) {
      @Override
      public void onIncrementalUpdate(final EObject incrementalUpdate) {
        printResponse("Incremental <XmiEObject> update from model server received: " + incrementalUpdate.toString());
        if (LOG.isInfoEnabled()) {
          LOG.info("Incremental update from the server recieved: " + incrementalUpdate.toString());
        }
      }
    };
    this.modelServerClient.subscribe(this.subscriptionID, listener);

  }
}
