package MPSListener.plugin.dataClasses.emf.ecore;

/*Generated by MPS */

import java.util.ArrayList;

public class Data {
  private String eclass;
  private String name;
  private String nsURI;
  private String nsPrefix;
  private ArrayList<EClassifier> eClassifiers;
  public Data() {
  }
  public Data(String eClass, String name, String nsURI, String nsPrefix, ArrayList<EClassifier> eClassifiers) {
    this.eclass = eClass;
    this.name = name;
    this.nsURI = nsURI;
    this.nsPrefix = nsPrefix;
    this.eClassifiers = eClassifiers;
  }

  public String getEClass() {
    return this.eclass;
  }
  public void setEClass(String eClass) {
    this.eclass = eClass;
  }
  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public String getNsURI() {
    return this.nsURI;
  }
  public void setNsURI(String nsURI) {
    this.nsURI = nsURI;
  }
  public String getNsPrefix() {
    return this.nsPrefix;
  }
  public void setNsPrefix(String nsPrefix) {
    this.nsPrefix = nsPrefix;
  }
  public ArrayList<EClassifier> getEClassifiers() {
    return this.eClassifiers;
  }
  public void setEClassifiers(ArrayList<EClassifier> eClassifiers) {
    this.eClassifiers = eClassifiers;
  }
}
