package MPSListener.plugin.dataClasses.emf.ecore;

/*Generated by MPS */

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;

public class EClassifier {
  private String eClass;
  private String name;

  @JsonProperty(value = "abstract")
  private boolean myAbstract;
  private ArrayList<EStructuralFeature> eStructuralFeatures;
  private ArrayList<ESuperType> eSuperTypes;

  public EClassifier() {
  }
  public EClassifier(String eClass, String name, boolean myAbstract, ArrayList<EStructuralFeature> eStructuralFeatures, ArrayList<ESuperType> eSuperTypes) {
    this.eClass = eClass;
    this.name = name;
    this.myAbstract = myAbstract;
    this.eStructuralFeatures = eStructuralFeatures;
    this.eSuperTypes = eSuperTypes;
  }

  public String getEClass() {
    return this.eClass;
  }
  public void setEClass(String eClass) {
    this.eClass = eClass;
  }
  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public boolean isMyAbstract() {
    return this.myAbstract;
  }
  public void setMyAbstract(boolean myAbstract) {
    this.myAbstract = myAbstract;
  }
  public ArrayList<EStructuralFeature> getEStructuralFeatures() {
    return this.eStructuralFeatures;
  }
  public void setEStructuralFeatures(ArrayList<EStructuralFeature> eStructuralFeatures) {
    this.eStructuralFeatures = eStructuralFeatures;
  }
  public ArrayList<ESuperType> getESuperTypes() {
    return this.eSuperTypes;
  }
  public void setESuperTypes(ArrayList<ESuperType> eSuperTypes) {
    this.eSuperTypes = eSuperTypes;
  }
}
