package MPSListener.plugin.dataClasses.emf.ecore;

/*Generated by MPS */


public class Ecore {
  private String type;
  private Data data;

  public Ecore() {
  }
  public Ecore(String type, Data data) {
    this.type = type;
    this.data = data;
  }
  public String getType() {
    return this.type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public Data getData() {
    return this.data;
  }
  public void setData(Data data) {
    this.data = data;
  }
}
