package MPSListener.plugin.dataClasses.emf.ecore;

/*Generated by MPS */

import java.util.Optional;

public class EStructuralFeature {
  private String eClass;
  private String name;
  private EType eType;
  private Integer upperBound;
  private boolean containment;
  private Integer lowerBound;

  public EStructuralFeature() {
  }
  public EStructuralFeature(String eClass, String name, EType eType, Integer upperBound, boolean containment, Integer lowerBound) {
    this.eClass = eClass;
    this.name = name;
    this.eType = eType;
    this.upperBound = upperBound;
    this.containment = containment;
    this.lowerBound = lowerBound;
  }
  public String getEClass() {
    return this.eClass;
  }
  public void setEClass(String eClass) {
    this.eClass = eClass;
  }
  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public EType getEType() {
    return this.eType;
  }
  public void setEType(EType eType) {
    this.eType = eType;
  }
  public Optional<Integer> getUpperBound() {
    return Optional.ofNullable(this.upperBound);
  }
  public void setUpperBound(Integer upperBound) {
    this.upperBound = upperBound;
  }
  public boolean isContainment() {
    return this.containment;
  }
  public void setContainment(boolean containment) {
    this.containment = containment;
  }
  public Optional<Integer> getLowerBound() {
    return Optional.ofNullable(this.lowerBound);
  }
  public void setLowerBound(Integer lowerBound) {
    this.lowerBound = lowerBound;
  }
}
