package MPSListener.plugin.dataClasses.emf.ecore;

/*Generated by MPS */


public class ESuperType {
  private String eClass;
  private String $ref;
  public ESuperType() {
  }
  public ESuperType(String eClass, String $ref) {
    this.eClass = eClass;
    this.$ref = $ref;
  }
  public String getEClass() {
    return this.eClass;
  }
  public void setEClass(String eClass) {
    this.eClass = eClass;
  }
  public String get$ref() {
    return this.$ref;
  }
  public void set$ref(String $ref) {
    this.$ref = $ref;
  }
}
