package MPSListener.plugin.specifyModel;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import com.intellij.util.messages.MessageBusConnection;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import javax.swing.KeyStroke;
import java.util.HashMap;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;
import javax.swing.JTree;
import javax.swing.JScrollPane;

public class instanceSelection_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private Project project;
  private MessageBusConnection messageBusConnection;
  public instanceSelection_Tool(Project project) {
    super(project, "instanceSelection", MapSequence.<String, KeyStroke>fromMapAndKeysArray(new HashMap<String, KeyStroke>(), "$default").withValues(KeyStroke.getKeyStroke("ctrl shift 0")), ICON, ToolWindowAnchor.TOP, false);
  }
  public void init(Project project) {
    super.init(project);
    instanceSelection_Tool.this.project = project;
  }
  public void dispose() {
    if (instanceSelection_Tool.this.messageBusConnection != null) {
      instanceSelection_Tool.this.messageBusConnection.disconnect();
    }
    super.dispose();
  }
  public JComponent getComponent() {
    JTree jtree = new JTree();
    return new JScrollPane(jtree);
  }
}
