package MPSListener.plugin.specifyModel;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;

public class JFrame {
  private MPS_LocalRepo localRepo;
  private SNode selectedNode;

  public JFrame(SNode node) {
    this.localRepo = MPS_LocalRepo.getInstance();
    this.selectedNode = node;
    System.out.println(node.getName());
  }

  public void runDialogbox() {
    try {
      SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
          JOptionPane.showConfirmDialog(null, "Are you sure you want to start collaborating this file?", "Select an option", JOptionPane.YES_NO_OPTION);
        }
      });
    } catch (Exception e) {
    }
  }
}
