package MPSListener.plugin.specifyModel;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import MPSListener.plugin.listener.MyListener;

public class StartPlugin {
  private MPS_LocalRepo localRepo;
  private JFrame frame;
  private SNode startingNode;
  private static StartPlugin instance;

  private static boolean isRunning = false;

  private StartPlugin(SNode startingNode) {
    this.localRepo = MPS_LocalRepo.getInstance();
    System.out.println(startingNode.getName());
    this.frame = new JFrame(startingNode);
    this.startingNode = startingNode;
  }
  public static StartPlugin getInstance(SNode startingNode) {
    if (instance == null) {
      instance = new StartPlugin(startingNode);
    }
    return instance;
  }

  public static StartPlugin getInstance() {
    return instance;
  }

  public void start() {
    this.localRepo.intialise();
    this.frame.runDialogbox();
    MyListener.getInstance(this.startingNode).start();
    isRunning = true;
  }

  public void setTarget(SNode target) {
    this.startingNode = target;
  }

  public void stop() {
    MyListener.getInstance(this.startingNode).stop();
    this.isRunning = false;

  }
  public static boolean isRunning() {
    return isRunning;
  }
}
