package MPSListener.plugin.dataClasses.emf.getModel;

/*Generated by MPS */

import java.util.List;

public class fileData {
  private String type;
  private String id;
  private String name;
  private List<input> inputs;
  private List<output> outputs;
  private List<states> states;
  private List<nodeEMF> nodeEmfList;

  public fileData(String tyoe, String id, String name, List<nodeEMF> nodeEmfList) {
    this.type = type;
    this.id = id;
    this.name = name;
    this.nodeEmfList = nodeEmfList;
  }

  public String getId() {
    return this.id;
  }
  public List<input> getInputs() {
    return this.inputs;
  }
  public List<output> getOutputs() {
    return this.outputs;
  }
  public List<states> getStates() {
    return this.states;
  }
  public List<nodeEMF> getNodeEmfList() {
    return this.nodeEmfList;
  }
}
