package MPSListener.plugin.dataClasses.emf.getModel;

/*Generated by MPS */

import java.util.HashMap;

public class nodeEMF {
  private String id;
  private String name;
  private String description;

  public nodeEMF(HashMap<String, String> nodeMap) {
    this.id = nodeMap.get("$id");
    this.name = nodeMap.get("name");
    this.description = nodeMap.get("description");
  }

  public String getId() {
    return this.id;
  }
  public String getName() {
    return this.name;
  }
  public String getDescription() {
    return this.description;
  }
}
