package MPSListener.plugin.dataClasses.emf.getModel;

/*Generated by MPS */

import java.util.HashMap;

public class output {
  private String id;
  private String name;
  private String description;

  public output(HashMap<String, String> outputMap) {
    this.id = outputMap.get("$id");
    this.name = outputMap.get("name");
    this.description = outputMap.get("description");
  }

  public String getId() {
    return this.id;
  }

  public String getName() {
    return this.name;
  }

  public String getDescription() {
    return this.description;
  }
}
