package MPSListener.plugin.initiate;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JOptionPane;

public class ConfirmationPopUp {
  private MPS_LocalRepo localRepo;
  private SNode selectedNode;
  private int userResult;

  public ConfirmationPopUp(SNode node) {
    this.selectedNode = node;
    userResult = -1;
  }

  public int confirm() {
    try {
      Thread toRun = new Thread(new Runnable() {
        @Override
        public void run() {
          userResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to start collaborating this file?", "Select an option", JOptionPane.YES_NO_OPTION);
        }
      });
      toRun.run();
    } catch (Exception e) {
    }
    return userResult;
  }
}
