package MPSListener.plugin.initiate;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.mps.openapi.model.SNode;
import MPSListener.plugin.emfModelServer.Client;
import MPSListener.plugin.listener.GlobalSModelListener;
import jetbrains.mps.project.Project;
import MPSListener.plugin.synchronise.MPS_LocalRepo;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;

public class StartPlugin {
  private static final Logger LOG = LogManager.getLogger(StartPlugin.class);

  private SNode startingNode;
  private static StartPlugin instance;
  private Client emfClient;
  private GlobalSModelListener mylistener;
  private static boolean isRunning = false;
  private java.util.logging.Logger logger;
  private Project currentProject;
  private MPS_LocalRepo mpsLocalRepo;

  private StartPlugin(SNode startingNode, Project project) {
    this.startingNode = startingNode;
    this.emfClient = Client.getInstance();
    this.mylistener = GlobalSModelListener.getInstance();
    this.logger = java.util.logging.Logger.getLogger(StartPlugin.class.getSimpleName());
    this.currentProject = project;
    this.mpsLocalRepo = MPS_LocalRepo.getInstance();
  }
  public static StartPlugin getInstance() {
    return instance;
  }


  public static StartPlugin getInstance(SNode node, Project project) {
    if (instance == null) {
      instance = new StartPlugin(node, project);
    }
    return instance;
  }

  public void changeTargetNode(SNode target) {
    this.startingNode = target;

  }
  public static boolean isRunning() {
    return isRunning;
  }

  public void start() {
    if (!(isRunning)) {
      // Ordering of the classes starting up **matter**
      LoggingRuntime.logMsgView(Level.WARN, "Initiating start up..", StartPlugin.class, null, null);
      this.mpsLocalRepo.start(this.startingNode);
      this.emfClient.start(this.startingNode, this.currentProject);
      this.mylistener.start(this.startingNode, this.currentProject);
      isRunning = true;
      LoggingRuntime.logMsgView(Level.WARN, "Start up successful.", StartPlugin.class, null, null);
    }
  }

  public void stop() {
    LoggingRuntime.logMsgView(Level.WARN, "Initiating shutdown..", StartPlugin.class, null, null);
    this.emfClient.stop();
    this.mylistener.stop();
    this.mpsLocalRepo.stop();
    this.isRunning = false;
    LoggingRuntime.logMsgView(Level.WARN, "Shutdown successful.", StartPlugin.class, null, null);
  }
}
